// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-accounts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_accounts_default = defineTool({
  name: "list_accounts",
  title: "List accounts",
  description: "List all of the signed-in user's Sonfi bank/investment/credit accounts with balances.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("accounts").select("id,name,type,institution,balance,currency,is_active").eq("is_active", true);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { accounts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-transactions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_transactions_default = defineTool2({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's recent transactions. Optionally filter by category or date range.",
  inputSchema: {
    limit: z.number().int().positive().default(50).describe("Max number of transactions to return."),
    category: z.string().optional().describe("Filter by category name."),
    since: z.string().optional().describe("ISO date; return transactions on or after this date."),
    until: z.string().optional().describe("ISO date; return transactions on or before this date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category, since, until }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser2(ctx).from("transactions").select("id,date,amount,type,category,merchant,description,account_id").order("date", { ascending: false }).limit(limit);
    if (category) q = q.eq("category", category);
    if (since) q = q.gte("date", since);
    if (until) q = q.lte("date", until);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-budgets.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_budgets_default = defineTool3({
  name: "list_budgets",
  title: "List budgets",
  description: "List the signed-in user's monthly budgets by category.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("budgets").select("*");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { budgets: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-goals.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_goals_default = defineTool4({
  name: "list_goals",
  title: "List savings goals",
  description: "List the signed-in user's savings goals with progress towards target.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser4(ctx).from("goals").select("*");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { goals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var financial_summary_default = defineTool5({
  name: "financial_summary",
  title: "Financial summary",
  description: "Return the signed-in user's overall financial snapshot: net worth, this-month income and expenses, and top spending categories.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const supabase = supabaseForUser5(ctx);
    const startOfMonth = /* @__PURE__ */ new Date();
    startOfMonth.setDate(1);
    startOfMonth.setHours(0, 0, 0, 0);
    const isoMonth = startOfMonth.toISOString().slice(0, 10);
    const [accountsRes, txRes] = await Promise.all([
      supabase.from("accounts").select("balance,type,is_active").eq("is_active", true),
      supabase.from("transactions").select("amount,type,category").gte("date", isoMonth)
    ]);
    if (accountsRes.error) return { content: [{ type: "text", text: accountsRes.error.message }], isError: true };
    if (txRes.error) return { content: [{ type: "text", text: txRes.error.message }], isError: true };
    const netWorth = (accountsRes.data ?? []).reduce((s, a) => s + Number(a.balance), 0);
    const income = (txRes.data ?? []).filter((t) => t.type === "income").reduce((s, t) => s + Number(t.amount), 0);
    const expenses = Math.abs(
      (txRes.data ?? []).filter((t) => t.type === "expense").reduce((s, t) => s + Number(t.amount), 0)
    );
    const catMap = {};
    for (const t of txRes.data ?? []) {
      if (t.type !== "expense") continue;
      catMap[t.category] = (catMap[t.category] ?? 0) + Math.abs(Number(t.amount));
    }
    const topCategories = Object.entries(catMap).sort(([, a], [, b]) => b - a).slice(0, 5).map(([category, amount]) => ({ category, amount }));
    const summary = { netWorth, monthIncome: income, monthExpenses: expenses, topCategories, currency: "GBP" };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ghontbbwexqxylwcsuhq";
var mcp_default = defineMcp({
  name: "sonfi-mcp",
  title: "Sonfi",
  version: "0.1.0",
  instructions: "Read the signed-in Sonfi user's personal finance data: accounts, transactions, budgets, savings goals, and an overall financial summary. Use `financial_summary` first for high-level context, then drill in with the other tools.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [financial_summary_default, list_accounts_default, list_transactions_default, list_budgets_default, list_goals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
